### ISSUE TITLE
@symbiotejs/symbiote package breaks uc-blocks 

### ISSUE THREAD

**Issue by karol-unum-la** [uploadcare/uc-blocks#212]
Hello 👋 

@nd0ut I cannot build my project because of the error:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/88664645/182728463-8929e1d9-21d5-4c3b-bdfd-a4703284dbc9.png">

I guess it is caused by this PR:

https://github.com/symbiotejs/symbiote.js/pull/43

**Comment by nd0ut** [comment]
Hey @karol-unum-la, we fixed it in `v0.0.7`. So sorry for breaking your build.

**Comment by karol-unum-la** [comment]
yes, `v0.7.0` fixes the issue, thanks
