### ISSUE TITLE
setUploadMetadata function not found

### ISSUE THREAD

**Issue by karol-unum-la** [uploadcare/uc-blocks#218]
@nd0ut I am trying to use setUploadMetadata, but unfortunately is not found. I started work on upload care widget in my project and I don't know why it stopped working. https://github.com/uploadcare/uc-blocks/issues/170

```js
import '@uploadcare/uc-blocks/web/lr-basic.min.css';

import { useEffect, useRef } from 'react';

import userStyles from './App.module.css';

export const Test = () => {
  const ref = useRef();

  useEffect(() => {
    // @ts-ignore
    ref.current?.setUploadMetadata({ foo: 'bar' });
  }, []);

  const classNames = ['lr-wgt-common', userStyles.uploaderCfg].join(' ');

  return (
    <lr-file-uploader-regular
      ref={ref}
      class={classNames}
    ></lr-file-uploader-regular>
  );
};
```

Screen:

![image](https://user-images.githubusercontent.com/88664645/182856456-f91bb516-ab2a-4771-98e6-909306dd1b03.png)

**Comment by nd0ut** [comment]
Hey @karol-unum-la,
sorry again for breaking your build.

Please use API though `<lr-upload-ctx-provider />` node reference:

```
<lr-file-uploader-regular class={classNames}>
  <lr-upload-ctx-provider ref={ref}></lr-upload-ctx-provider>
</lr-file-uploader-regular>
```

**Comment by karol-unum-la** [comment]
it works
